name: check
on:
  schedule:
    - cron: "*/05 * * * *"

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching p ip dependencies
      - run: pip install -r requirements.txt
      - run: python check.py